# Generated by Django 5.0.7 on 2024-07-26 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lembretes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('data_notificacao', models.DateTimeField()),
                ('lembrete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lembretes.lembrete')),
            ],
        ),
    ]
