# Generated by Django 5.0.7 on 2024-07-30 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_notificacao_user_alter_notificacao_lembrete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='data_notificacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
