# Generated by Django 5.0.7 on 2024-07-30 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0009_rename_usuario_lembrete_user'),
        ('notificacoes', '0004_alter_notificacao_data_notificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='lembrete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lembretes.lembrete'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='mensagem',
            field=models.CharField(max_length=255),
        ),
    ]
