# Generated by Django 5.0.7 on 2024-07-27 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_remove_categoria_prioridade_and_more'),
        ('lembretes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembrete',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria'),
        ),
        migrations.AlterField(
            model_name='lembrete',
            name='prioridade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lembrete',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
