# Generated by Django 5.0.7 on 2024-07-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0003_remove_lembrete_categoria_lembrete_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembrete',
            name='prioridade',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Média'), (3, 'Baixa')]),
        ),
    ]
