# Generated by Django 5.0.7 on 2024-07-28 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_lembrete'),
        ('lembretes', '0004_alter_lembrete_prioridade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lembrete',
            name='categoria',
        ),
        migrations.AddField(
            model_name='lembrete',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='categorias.categoria'),
        ),
    ]
