# Generated by Django 5.0.7 on 2024-07-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0007_alter_lembrete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lembrete',
            old_name='user',
            new_name='usuario',
        ),
    ]
