# Generated by Django 5.0.7 on 2024-08-02 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0011_lembrete_listas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('lembrete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='lembretes.lembrete')),
            ],
        ),
    ]
