# Generated by Django 5.0.7 on 2024-07-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_remove_categoria_prioridade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_lembrete', models.DateTimeField()),
                ('prioridade', models.CharField(max_length=50)),
                ('categoria', models.ManyToManyField(to='categorias.categoria')),
            ],
        ),
    ]
