# Generated by Django 5.0.7 on 2024-07-29 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nome_completo',
        ),
    ]
