# Generated by Django 5.0.7 on 2024-08-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anexos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anexo',
        ),
    ]
