# Generated by Django 5.0.7 on 2024-08-02 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anexos', '0002_delete_anexo'),
        ('lembretes', '0012_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('descricao', models.CharField(max_length=255)),
                ('lembrete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lembretes.lembrete')),
            ],
        ),
    ]
